#Written by Ayman Islam (https://www.linkedin.com/in/aymansislam/) between 2017-2019

level1 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

level2 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

level3 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

level4 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

level5 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

level8 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

level6 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

#Disappearing maze level
level7 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W           D                        D   W",
    "W       DDDDD                        D   W",
    "W    DDDD              DDDDDDDD   D  D   W",
    "W    D            DDDDDDDDDDDDD   D  D   W",
    "W    D                        D   D  DDDDW",
    "W    D                        D   D      W",
    "W    DDDDDDDDDDDDDDDDDDDD     D   D      W",
    "W                       D     D   DDDDDDDW",
    "W                       D     D          W",
    "W        DDDDDDDDDDDDDDDD    DD          W",
    "W        D                   D           W",
    "W        D                   D           W",
    "W        D   DDDDDDDDDDDDDDDD            W",
    "W        D   D                           W",
    "W        D   D                           W",
    "W        D   D                           W",
    "W        D   DDDDDDDDDDDDDDDDDDDDDDDDD   W",
    "W        D                           D   W",
    "W        D                           D   W",
    "W        DDDDDDDDDDDDDDDDDDDDDD      D   W",
    "W                             D      D   W",
    "W                         DDDDD      D   W",
    "W                DDDDDDDDDD          D   W",
    "W                D                   D   W",
    "W                D                DDDD   W",
    "W                D          DDDDDD       W",
    "W                D     DDDDD             W",
    "W                D    D                  W",
    "W                D   D                   W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

level9 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
]

#Boss fight level
level10 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                        W",
    "W                         W              W",
    "W                         W              W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W        W                               W",
    "W        W                               W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                W                       W",
    "W                W                       W",
    "W                W                       W",
    "W                                        W",
    "W                           W            W",
    "W                           W            W",
    "W                           W            W",
    "W                           W            W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W       W                                W",
    "W       W                                W",
    "W       W                                W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

#Shop level
levelSHOP = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W           WWW           WWW            W",
    "W           W W           W W            W",
    "W           W W           W W            W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "W                                        W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

#Maze level
level6 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W             WWW                        W",
    "W             W W       WWWWWWWWWW       W",
    "W             W W       WN      NW       W",
    "W    WWWWWWWWWW W    WWWW WWWWWW WWWWW   W",
    "W    WN        NW    WN  NW    WN   NW   W",
    "W    W WWWWWWWWWW    W WWWW    WWWWWWW   W",
    "W    W W       WWWWWWW W                 W",
    "W    W W       WN     NW                 W",
    "W    W W       W WWWWWWW                 W",
    "W    W WWWWWWWWW W                       W",
    "W    WN    N    NW                       W",
    "W    WWWWWWWWWWW WWWWWWWWWWWWWWWWWWWW    W",
    "W              WNN N N      N      NW    W",
    "W              WW W W WWWWWWWWWWWWWWW    W",
    "W               W W W W                  W",
    "W        WWWWWWWW W W WWWWWWWWW          W",
    "W        WN      NW WNN      NW          W",
    "W        W WWWWWWWW WW WWWWWW W          W",
    "W        W W       N W W    W WWWWWWW    W",
    "W        W WWWWWWWWWWW W    WN     NW    W",
    "W        W WWWWWWWWWWW W    W WWWWWWW    W",
    "W        W WWWWWWWWWWW W    W W          W",
    "W   WWWWWWN      N    NW    W W          W",
    "W   WN    NWWWWWW WWWWWW    W WWWWWWWW   W",
    "W   W WWWWWW    W WWWWWWWW  WN      NW   W",
    "W   W W         WN      NW  WWWWWWWWWW   W",
    "W   WNW         WWWWWWWW W               W",
    "W   WWW                W W               W",
    "W                      WWW               W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

#The map
levelMAP = [
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                WWW                       ",
    "                WWW                       ",
    "                WWW                       ",
    "                                          ",
    "                WWW WWWWW                 ",
    "                WWW WWWWW                 ",
    "                                          ",
    "               WWWWW                      ",
    "       WWW WWW WWWWW WWW WWW              ",
    "       WWW WWW WWWWW WWW WWW              ",
    "       WWW     WWWWW     WWW              ",
    "                                          ",
    "                WWW                       ",
    "                WWW                       ",
    "                                          ",
    "                 WWWWWW                   ",
    "                 WWWWWW                   ",
    "                 WWWWWW                   ",
    "                 WWWWWW                   ",
    "                 WWWWWW                   ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
    "                                          ",
]
